#!/bin/bash -eu

cd ${0%/*}

MASTER_KEY=key/tarsnap.key

if [ ! -f $MASTER_KEY ]; then
  echo -n "Enter machine name (`hostname`): "
  read machine_name

  echo -n "Enter you tarsnap email address: "
  read email

  docker/tarsnap keygen "${email}" "${machine_name:-`hostname`}"
  cat <<EOF

*******************************************************************************
*******************************************************************************
** IMPORTANT!
**
** Store your ${MASTER_KEY} somewhere safe.
** If you lose tarsnap.key, you will not be able to access your archived data.
*******************************************************************************
*******************************************************************************

EOF
fi

echo "Creating write-only key.."
docker/tarsnap keymgmt-w
echo "write-only key created!"
