#!/bin/bash -eu

cd ${0%/*}

if [[ $# -lt 2 ]]; then
  echo "Usage: ${0##*/} archive-name [files | directories]" >&2
  exit 1
fi

archive_name=${1}
restore_paths=${@:2}

docker/tarsnap restore "${archive_name}" "${restore_paths[@]}"
echo "Files successfully restored"
