#!/bin/bash -eu

cd ..

BACKUP_NAME=${1:?}
BACKUP_PATH=${2:?}

WRITE_ONLY_KEY=/tarsnap/write_only.key
CACHE_DIR=/tarsnap/cache

if [[ -r backups/$BACKUP_PATH ]]; then
  docker-compose run --rm tarsnap_wo \
    tarsnap \
    --keyfile $WRITE_ONLY_KEY \
    --cachedir $CACHE_DIR \
    -c -f "$BACKUP_NAME" "$BACKUP_PATH"
else
  echo "File not found: backups/$BACKUP_PATH" >&2
  exit 1
fi