#!/bin/bash -eu

cd ..

MASTER_KEY=/key/tarsnap.key
CACHE_DIR=/tarsnap/cache

echo "Listing archives"

docker-compose run --rm tarsnap_rw \
  tarsnap \
  --keyfile $MASTER_KEY \
  --cachedir $CACHE_DIR \
  --list-archives

echo -n "Continue? [y/N]: "
read yes_no

if [[ $yes_no == "y" || $yes_no == "yes" ]]; then
  docker-compose run --rm tarsnap_rw \
    tarsnap \
    --keyfile $MASTER_KEY \
    --cachedir $CACHE_DIR \
    --nuke
fi