#!/bin/bash -eu

cd ..

BACKUP_NAME=${1:?}
BACKUP_PATH=${2:?}

MASTER_KEY=/key/tarsnap.key
CACHE_DIR=/tarsnap/cache

docker-compose run --rm tarsnap_rw \
  tarsnap \
  -x \
  --keyfile $MASTER_KEY \
  --cachedir $CACHE_DIR \
  -f "$BACKUP_NAME" "$BACKUP_PATH"
